# -*- coding: utf-8 -*-
"""generate_pairs_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOLC4IWDW4GhBrW6juCWGqQc9Dj0KOuo
"""

import os
import csv

# 경로 설정
source_dir = "data/source"
target_dir = "data/target"
output_csv = "data/pairs.csv"

# 기본 템플릿
default_source_prompt = "a photo of a cat"
default_target_prompt = "a photo of a dog"

# pose match는 수작업이 아니면 모두 True 또는 False로 설정
default_pose_match = "True"

# 소스 디렉토리 기준 정렬된 파일 리스트
source_images = sorted([f for f in os.listdir(source_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
target_images = sorted([f for f in os.listdir(target_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])

assert len(source_images) == len(target_images), "source와 target 이미지 수가 맞지 않습니다."

# pairs.csv 작성
with open(output_csv, mode='w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['idx', 'source_img', 'source_prompt', 'target_img', 'target_prompt', 'pose_match'])

    for idx, (src, tgt) in enumerate(zip(source_images, target_images), 1):
        row = [
            f"{idx:03d}",
            os.path.join("source", src),
            default_source_prompt,
            os.path.join("target", tgt),
            default_target_prompt,
            default_pose_match
        ]
        writer.writerow(row)

print(f"✅ pairs.csv 생성 완료: {output_csv}")